version: '2.2'

services:
  php:
    image: php:8.1.1
    entrypoint: tail -f /dev/null
    volumes:
    - ./:/var/www/html
    working_dir: /var/www/html
  composer:
      image: composer/composer:2.0.8
      command: install
      volumes: 
        - ./:/app
